// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// NewAddDelayParams creates a new AddDelayParams object
// with the default values initialized.
func NewAddDelayParams() *AddDelayParams {
	var ()
	return &AddDelayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddDelayParamsWithTimeout creates a new AddDelayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddDelayParamsWithTimeout(timeout time.Duration) *AddDelayParams {
	var ()
	return &AddDelayParams{

		timeout: timeout,
	}
}

// NewAddDelayParamsWithContext creates a new AddDelayParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddDelayParamsWithContext(ctx context.Context) *AddDelayParams {
	var ()
	return &AddDelayParams{

		Context: ctx,
	}
}

// NewAddDelayParamsWithHTTPClient creates a new AddDelayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddDelayParamsWithHTTPClient(client *http.Client) *AddDelayParams {
	var ()
	return &AddDelayParams{
		HTTPClient: client,
	}
}

/*AddDelayParams contains all the parameters to send to the API endpoint
for the add delay operation typically these are written to a http.Request
*/
type AddDelayParams struct {

	/*Body*/
	Body *models.ModelAddDelayStageRequest
	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add delay params
func (o *AddDelayParams) WithTimeout(timeout time.Duration) *AddDelayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add delay params
func (o *AddDelayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add delay params
func (o *AddDelayParams) WithContext(ctx context.Context) *AddDelayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add delay params
func (o *AddDelayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add delay params
func (o *AddDelayParams) WithHTTPClient(client *http.Client) *AddDelayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add delay params
func (o *AddDelayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add delay params
func (o *AddDelayParams) WithBody(body *models.ModelAddDelayStageRequest) *AddDelayParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add delay params
func (o *AddDelayParams) SetBody(body *models.ModelAddDelayStageRequest) {
	o.Body = body
}

// WithFlowID adds the flowID to the add delay params
func (o *AddDelayParams) WithFlowID(flowID string) *AddDelayParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the add delay params
func (o *AddDelayParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *AddDelayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
