// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// AddValueStageReader is a Reader for the AddValueStage structure.
type AddValueStageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddValueStageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddValueStageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddValueStageOK creates a AddValueStageOK with default headers values
func NewAddValueStageOK() *AddValueStageOK {
	return &AddValueStageOK{}
}

/*AddValueStageOK handles this case with default header values.

AddValueStageOK add value stage o k
*/
type AddValueStageOK struct {
	Payload *models.ModelAddStageResponse
}

func (o *AddValueStageOK) Error() string {
	return fmt.Sprintf("[POST /v1/flows/{flow_id}/value][%d] addValueStageOK  %+v", 200, o.Payload)
}

func (o *AddValueStageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelAddStageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
