// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// AddInvokeFunctionReader is a Reader for the AddInvokeFunction structure.
type AddInvokeFunctionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddInvokeFunctionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddInvokeFunctionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddInvokeFunctionOK creates a AddInvokeFunctionOK with default headers values
func NewAddInvokeFunctionOK() *AddInvokeFunctionOK {
	return &AddInvokeFunctionOK{}
}

/*AddInvokeFunctionOK handles this case with default header values.

AddInvokeFunctionOK add invoke function o k
*/
type AddInvokeFunctionOK struct {
	Payload *models.ModelAddStageResponse
}

func (o *AddInvokeFunctionOK) Error() string {
	return fmt.Sprintf("[POST /v1/flows/{flow_id}/invoke][%d] addInvokeFunctionOK  %+v", 200, o.Payload)
}

func (o *AddInvokeFunctionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelAddStageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
