// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// NewAddValueStageParams creates a new AddValueStageParams object
// with the default values initialized.
func NewAddValueStageParams() *AddValueStageParams {
	var ()
	return &AddValueStageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddValueStageParamsWithTimeout creates a new AddValueStageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddValueStageParamsWithTimeout(timeout time.Duration) *AddValueStageParams {
	var ()
	return &AddValueStageParams{

		timeout: timeout,
	}
}

// NewAddValueStageParamsWithContext creates a new AddValueStageParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddValueStageParamsWithContext(ctx context.Context) *AddValueStageParams {
	var ()
	return &AddValueStageParams{

		Context: ctx,
	}
}

// NewAddValueStageParamsWithHTTPClient creates a new AddValueStageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddValueStageParamsWithHTTPClient(client *http.Client) *AddValueStageParams {
	var ()
	return &AddValueStageParams{
		HTTPClient: client,
	}
}

/*AddValueStageParams contains all the parameters to send to the API endpoint
for the add value stage operation typically these are written to a http.Request
*/
type AddValueStageParams struct {

	/*Body*/
	Body *models.ModelAddCompletedValueStageRequest
	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add value stage params
func (o *AddValueStageParams) WithTimeout(timeout time.Duration) *AddValueStageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add value stage params
func (o *AddValueStageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add value stage params
func (o *AddValueStageParams) WithContext(ctx context.Context) *AddValueStageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add value stage params
func (o *AddValueStageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add value stage params
func (o *AddValueStageParams) WithHTTPClient(client *http.Client) *AddValueStageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add value stage params
func (o *AddValueStageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add value stage params
func (o *AddValueStageParams) WithBody(body *models.ModelAddCompletedValueStageRequest) *AddValueStageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add value stage params
func (o *AddValueStageParams) SetBody(body *models.ModelAddCompletedValueStageRequest) {
	o.Body = body
}

// WithFlowID adds the flowID to the add value stage params
func (o *AddValueStageParams) WithFlowID(flowID string) *AddValueStageParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the add value stage params
func (o *AddValueStageParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *AddValueStageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
