// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// NewAddInvokeFunctionParams creates a new AddInvokeFunctionParams object
// with the default values initialized.
func NewAddInvokeFunctionParams() *AddInvokeFunctionParams {
	var ()
	return &AddInvokeFunctionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddInvokeFunctionParamsWithTimeout creates a new AddInvokeFunctionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddInvokeFunctionParamsWithTimeout(timeout time.Duration) *AddInvokeFunctionParams {
	var ()
	return &AddInvokeFunctionParams{

		timeout: timeout,
	}
}

// NewAddInvokeFunctionParamsWithContext creates a new AddInvokeFunctionParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddInvokeFunctionParamsWithContext(ctx context.Context) *AddInvokeFunctionParams {
	var ()
	return &AddInvokeFunctionParams{

		Context: ctx,
	}
}

// NewAddInvokeFunctionParamsWithHTTPClient creates a new AddInvokeFunctionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddInvokeFunctionParamsWithHTTPClient(client *http.Client) *AddInvokeFunctionParams {
	var ()
	return &AddInvokeFunctionParams{
		HTTPClient: client,
	}
}

/*AddInvokeFunctionParams contains all the parameters to send to the API endpoint
for the add invoke function operation typically these are written to a http.Request
*/
type AddInvokeFunctionParams struct {

	/*Body*/
	Body *models.ModelAddInvokeFunctionStageRequest
	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add invoke function params
func (o *AddInvokeFunctionParams) WithTimeout(timeout time.Duration) *AddInvokeFunctionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add invoke function params
func (o *AddInvokeFunctionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add invoke function params
func (o *AddInvokeFunctionParams) WithContext(ctx context.Context) *AddInvokeFunctionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add invoke function params
func (o *AddInvokeFunctionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add invoke function params
func (o *AddInvokeFunctionParams) WithHTTPClient(client *http.Client) *AddInvokeFunctionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add invoke function params
func (o *AddInvokeFunctionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add invoke function params
func (o *AddInvokeFunctionParams) WithBody(body *models.ModelAddInvokeFunctionStageRequest) *AddInvokeFunctionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add invoke function params
func (o *AddInvokeFunctionParams) SetBody(body *models.ModelAddInvokeFunctionStageRequest) {
	o.Body = body
}

// WithFlowID adds the flowID to the add invoke function params
func (o *AddInvokeFunctionParams) WithFlowID(flowID string) *AddInvokeFunctionParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the add invoke function params
func (o *AddInvokeFunctionParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *AddInvokeFunctionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
