// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCommitParams creates a new CommitParams object
// with the default values initialized.
func NewCommitParams() *CommitParams {
	var ()
	return &CommitParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCommitParamsWithTimeout creates a new CommitParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCommitParamsWithTimeout(timeout time.Duration) *CommitParams {
	var ()
	return &CommitParams{

		timeout: timeout,
	}
}

// NewCommitParamsWithContext creates a new CommitParams object
// with the default values initialized, and the ability to set a context for a request
func NewCommitParamsWithContext(ctx context.Context) *CommitParams {
	var ()
	return &CommitParams{

		Context: ctx,
	}
}

// NewCommitParamsWithHTTPClient creates a new CommitParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCommitParamsWithHTTPClient(client *http.Client) *CommitParams {
	var ()
	return &CommitParams{
		HTTPClient: client,
	}
}

/*CommitParams contains all the parameters to send to the API endpoint
for the commit operation typically these are written to a http.Request
*/
type CommitParams struct {

	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the commit params
func (o *CommitParams) WithTimeout(timeout time.Duration) *CommitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the commit params
func (o *CommitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the commit params
func (o *CommitParams) WithContext(ctx context.Context) *CommitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the commit params
func (o *CommitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the commit params
func (o *CommitParams) WithHTTPClient(client *http.Client) *CommitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the commit params
func (o *CommitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFlowID adds the flowID to the commit params
func (o *CommitParams) WithFlowID(flowID string) *CommitParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the commit params
func (o *CommitParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *CommitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
