// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// CommitReader is a Reader for the Commit structure.
type CommitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CommitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCommitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCommitOK creates a CommitOK with default headers values
func NewCommitOK() *CommitOK {
	return &CommitOK{}
}

/*CommitOK handles this case with default header values.

CommitOK commit o k
*/
type CommitOK struct {
	Payload *models.ModelGraphRequestProcessedResponse
}

func (o *CommitOK) Error() string {
	return fmt.Sprintf("[POST /v1/flows/{flow_id}/commit][%d] commitOK  %+v", 200, o.Payload)
}

func (o *CommitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelGraphRequestProcessedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
