// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// CompleteStageExternallyReader is a Reader for the CompleteStageExternally structure.
type CompleteStageExternallyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompleteStageExternallyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCompleteStageExternallyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCompleteStageExternallyOK creates a CompleteStageExternallyOK with default headers values
func NewCompleteStageExternallyOK() *CompleteStageExternallyOK {
	return &CompleteStageExternallyOK{}
}

/*CompleteStageExternallyOK handles this case with default header values.

CompleteStageExternallyOK complete stage externally o k
*/
type CompleteStageExternallyOK struct {
	Payload *models.ModelCompleteStageExternallyResponse
}

func (o *CompleteStageExternallyOK) Error() string {
	return fmt.Sprintf("[POST /v1/flows/{flow_id}/stages/{stage_id}/complete][%d] completeStageExternallyOK  %+v", 200, o.Payload)
}

func (o *CompleteStageExternallyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelCompleteStageExternallyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
