// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// NewCompleteStageExternallyParams creates a new CompleteStageExternallyParams object
// with the default values initialized.
func NewCompleteStageExternallyParams() *CompleteStageExternallyParams {
	var ()
	return &CompleteStageExternallyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompleteStageExternallyParamsWithTimeout creates a new CompleteStageExternallyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompleteStageExternallyParamsWithTimeout(timeout time.Duration) *CompleteStageExternallyParams {
	var ()
	return &CompleteStageExternallyParams{

		timeout: timeout,
	}
}

// NewCompleteStageExternallyParamsWithContext creates a new CompleteStageExternallyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompleteStageExternallyParamsWithContext(ctx context.Context) *CompleteStageExternallyParams {
	var ()
	return &CompleteStageExternallyParams{

		Context: ctx,
	}
}

// NewCompleteStageExternallyParamsWithHTTPClient creates a new CompleteStageExternallyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompleteStageExternallyParamsWithHTTPClient(client *http.Client) *CompleteStageExternallyParams {
	var ()
	return &CompleteStageExternallyParams{
		HTTPClient: client,
	}
}

/*CompleteStageExternallyParams contains all the parameters to send to the API endpoint
for the complete stage externally operation typically these are written to a http.Request
*/
type CompleteStageExternallyParams struct {

	/*Body*/
	Body *models.ModelCompleteStageExternallyRequest
	/*FlowID*/
	FlowID string
	/*StageID*/
	StageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the complete stage externally params
func (o *CompleteStageExternallyParams) WithTimeout(timeout time.Duration) *CompleteStageExternallyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the complete stage externally params
func (o *CompleteStageExternallyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the complete stage externally params
func (o *CompleteStageExternallyParams) WithContext(ctx context.Context) *CompleteStageExternallyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the complete stage externally params
func (o *CompleteStageExternallyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the complete stage externally params
func (o *CompleteStageExternallyParams) WithHTTPClient(client *http.Client) *CompleteStageExternallyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the complete stage externally params
func (o *CompleteStageExternallyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the complete stage externally params
func (o *CompleteStageExternallyParams) WithBody(body *models.ModelCompleteStageExternallyRequest) *CompleteStageExternallyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the complete stage externally params
func (o *CompleteStageExternallyParams) SetBody(body *models.ModelCompleteStageExternallyRequest) {
	o.Body = body
}

// WithFlowID adds the flowID to the complete stage externally params
func (o *CompleteStageExternallyParams) WithFlowID(flowID string) *CompleteStageExternallyParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the complete stage externally params
func (o *CompleteStageExternallyParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WithStageID adds the stageID to the complete stage externally params
func (o *CompleteStageExternallyParams) WithStageID(stageID string) *CompleteStageExternallyParams {
	o.SetStageID(stageID)
	return o
}

// SetStageID adds the stageId to the complete stage externally params
func (o *CompleteStageExternallyParams) SetStageID(stageID string) {
	o.StageID = stageID
}

// WriteToRequest writes these params to a swagger request
func (o *CompleteStageExternallyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	// path param stage_id
	if err := r.SetPathParam("stage_id", o.StageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
