// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// GetGraphStateReader is a Reader for the GetGraphState structure.
type GetGraphStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGraphStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGraphStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGraphStateOK creates a GetGraphStateOK with default headers values
func NewGetGraphStateOK() *GetGraphStateOK {
	return &GetGraphStateOK{}
}

/*GetGraphStateOK handles this case with default header values.

GetGraphStateOK get graph state o k
*/
type GetGraphStateOK struct {
	Payload *models.ModelGetGraphStateResponse
}

func (o *GetGraphStateOK) Error() string {
	return fmt.Sprintf("[GET /v1/flows/{flow_id}][%d] getGraphStateOK  %+v", 200, o.Payload)
}

func (o *GetGraphStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelGetGraphStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
