// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGraphStateParams creates a new GetGraphStateParams object
// with the default values initialized.
func NewGetGraphStateParams() *GetGraphStateParams {
	var ()
	return &GetGraphStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGraphStateParamsWithTimeout creates a new GetGraphStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGraphStateParamsWithTimeout(timeout time.Duration) *GetGraphStateParams {
	var ()
	return &GetGraphStateParams{

		timeout: timeout,
	}
}

// NewGetGraphStateParamsWithContext creates a new GetGraphStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGraphStateParamsWithContext(ctx context.Context) *GetGraphStateParams {
	var ()
	return &GetGraphStateParams{

		Context: ctx,
	}
}

// NewGetGraphStateParamsWithHTTPClient creates a new GetGraphStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGraphStateParamsWithHTTPClient(client *http.Client) *GetGraphStateParams {
	var ()
	return &GetGraphStateParams{
		HTTPClient: client,
	}
}

/*GetGraphStateParams contains all the parameters to send to the API endpoint
for the get graph state operation typically these are written to a http.Request
*/
type GetGraphStateParams struct {

	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get graph state params
func (o *GetGraphStateParams) WithTimeout(timeout time.Duration) *GetGraphStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get graph state params
func (o *GetGraphStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get graph state params
func (o *GetGraphStateParams) WithContext(ctx context.Context) *GetGraphStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get graph state params
func (o *GetGraphStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get graph state params
func (o *GetGraphStateParams) WithHTTPClient(client *http.Client) *GetGraphStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get graph state params
func (o *GetGraphStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFlowID adds the flowID to the get graph state params
func (o *GetGraphStateParams) WithFlowID(flowID string) *GetGraphStateParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the get graph state params
func (o *GetGraphStateParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGraphStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param flow_id
	if err := r.SetPathParam("flow_id", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
