// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fnproject/flow-lib-go/models"
)

// StreamEventsReader is a Reader for the StreamEvents structure.
type StreamEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StreamEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStreamEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStreamEventsOK creates a StreamEventsOK with default headers values
func NewStreamEventsOK() *StreamEventsOK {
	return &StreamEventsOK{}
}

/*StreamEventsOK handles this case with default header values.

(streaming responses)
*/
type StreamEventsOK struct {
	Payload *models.ModelGraphEvent
}

func (o *StreamEventsOK) Error() string {
	return fmt.Sprintf("[GET /v1/flows/{flow_id}/stream][%d] streamEventsOK  %+v", 200, o.Payload)
}

func (o *StreamEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelGraphEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
