// Code generated by go-swagger; DO NOT EDIT.

package flow_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStreamLifecycleParams creates a new StreamLifecycleParams object
// with the default values initialized.
func NewStreamLifecycleParams() *StreamLifecycleParams {

	return &StreamLifecycleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStreamLifecycleParamsWithTimeout creates a new StreamLifecycleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStreamLifecycleParamsWithTimeout(timeout time.Duration) *StreamLifecycleParams {

	return &StreamLifecycleParams{

		timeout: timeout,
	}
}

// NewStreamLifecycleParamsWithContext creates a new StreamLifecycleParams object
// with the default values initialized, and the ability to set a context for a request
func NewStreamLifecycleParamsWithContext(ctx context.Context) *StreamLifecycleParams {

	return &StreamLifecycleParams{

		Context: ctx,
	}
}

// NewStreamLifecycleParamsWithHTTPClient creates a new StreamLifecycleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStreamLifecycleParamsWithHTTPClient(client *http.Client) *StreamLifecycleParams {

	return &StreamLifecycleParams{
		HTTPClient: client,
	}
}

/*StreamLifecycleParams contains all the parameters to send to the API endpoint
for the stream lifecycle operation typically these are written to a http.Request
*/
type StreamLifecycleParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stream lifecycle params
func (o *StreamLifecycleParams) WithTimeout(timeout time.Duration) *StreamLifecycleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stream lifecycle params
func (o *StreamLifecycleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stream lifecycle params
func (o *StreamLifecycleParams) WithContext(ctx context.Context) *StreamLifecycleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stream lifecycle params
func (o *StreamLifecycleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stream lifecycle params
func (o *StreamLifecycleParams) WithHTTPClient(client *http.Client) *StreamLifecycleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stream lifecycle params
func (o *StreamLifecycleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StreamLifecycleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
