// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetGraphStateResponseStageRepresentation get graph state response stage representation
// swagger:model GetGraphStateResponseStageRepresentation
type GetGraphStateResponseStageRepresentation struct {

	// dependencies
	Dependencies []string `json:"dependencies"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get graph state response stage representation
func (m *GetGraphStateResponseStageRepresentation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDependencies(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetGraphStateResponseStageRepresentation) validateDependencies(formats strfmt.Registry) error {

	if swag.IsZero(m.Dependencies) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetGraphStateResponseStageRepresentation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetGraphStateResponseStageRepresentation) UnmarshalBinary(b []byte) error {
	var res GetGraphStateResponseStageRepresentation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
