// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelBlobDatum BlobDatum holds a reference to a blob the associated blob store
// swagger:model modelBlobDatum
type ModelBlobDatum struct {

	// blob id
	BlobID string `json:"blob_id,omitempty"`

	// content type
	ContentType string `json:"content_type,omitempty"`

	// length
	Length int64 `json:"length,omitempty,string"`
}

// Validate validates this model blob datum
func (m *ModelBlobDatum) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelBlobDatum) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelBlobDatum) UnmarshalBinary(b []byte) error {
	var res ModelBlobDatum
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
