// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelCreateGraphRequest model create graph request
// swagger:model modelCreateGraphRequest
type ModelCreateGraphRequest struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// function id
	FunctionID string `json:"function_id,omitempty"`
}

// Validate validates this model create graph request
func (m *ModelCreateGraphRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelCreateGraphRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelCreateGraphRequest) UnmarshalBinary(b []byte) error {
	var res ModelCreateGraphRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
