// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelStageRefDatum StageRefDatum represents a reference to another stage in the graph
// swagger:model modelStageRefDatum
type ModelStageRefDatum struct {

	// stage id
	StageID string `json:"stage_id,omitempty"`
}

// Validate validates this model stage ref datum
func (m *ModelStageRefDatum) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelStageRefDatum) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelStageRefDatum) UnmarshalBinary(b []byte) error {
	var res ModelStageRefDatum
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
