// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelCompleteStageExternallyResponse model complete stage externally response
// swagger:model modelCompleteStageExternallyResponse
type ModelCompleteStageExternallyResponse struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// successful
	Successful bool `json:"successful,omitempty"`
}

// Validate validates this model complete stage externally response
func (m *ModelCompleteStageExternallyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelCompleteStageExternallyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelCompleteStageExternallyResponse) UnmarshalBinary(b []byte) error {
	var res ModelCompleteStageExternallyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
