// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelCompleteStageExternallyRequest CompleteStageExternallyRequest marks an existing stage as complete with a specific value
// swagger:model modelCompleteStageExternallyRequest
type ModelCompleteStageExternallyRequest struct {

	// caller id
	CallerID string `json:"caller_id,omitempty"`

	// code location
	CodeLocation string `json:"code_location,omitempty"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// value
	Value *ModelCompletionResult `json:"value,omitempty"`
}

// Validate validates this model complete stage externally request
func (m *ModelCompleteStageExternallyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelCompleteStageExternallyRequest) validateValue(formats strfmt.Registry) error {

	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if m.Value != nil {

		if err := m.Value.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("value")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelCompleteStageExternallyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelCompleteStageExternallyRequest) UnmarshalBinary(b []byte) error {
	var res ModelCompleteStageExternallyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
