// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelStageAddedEvent A stage was added to the graph
// swagger:model modelStageAddedEvent
type ModelStageAddedEvent struct {

	// caller id
	CallerID string `json:"caller_id,omitempty"`

	// closure
	Closure *ModelBlobDatum `json:"closure,omitempty"`

	// code location
	CodeLocation string `json:"code_location,omitempty"`

	// dependencies
	Dependencies []string `json:"dependencies"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// op
	Op ModelCompletionOperation `json:"op,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// ts
	Ts strfmt.DateTime `json:"ts,omitempty"`
}

// Validate validates this model stage added event
func (m *ModelStageAddedEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClosure(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDependencies(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOp(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelStageAddedEvent) validateClosure(formats strfmt.Registry) error {

	if swag.IsZero(m.Closure) { // not required
		return nil
	}

	if m.Closure != nil {

		if err := m.Closure.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("closure")
			}
			return err
		}
	}

	return nil
}

func (m *ModelStageAddedEvent) validateDependencies(formats strfmt.Registry) error {

	if swag.IsZero(m.Dependencies) { // not required
		return nil
	}

	return nil
}

func (m *ModelStageAddedEvent) validateOp(formats strfmt.Registry) error {

	if swag.IsZero(m.Op) { // not required
		return nil
	}

	if err := m.Op.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("op")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelStageAddedEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelStageAddedEvent) UnmarshalBinary(b []byte) error {
	var res ModelStageAddedEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
