// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelGetGraphStateResponse model get graph state response
// swagger:model modelGetGraphStateResponse
type ModelGetGraphStateResponse struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// function id
	FunctionID string `json:"function_id,omitempty"`

	// stages
	Stages ModelGetGraphStateResponseStages `json:"stages,omitempty"`
}

// Validate validates this model get graph state response
func (m *ModelGetGraphStateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGetGraphStateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGetGraphStateResponse) UnmarshalBinary(b []byte) error {
	var res ModelGetGraphStateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
