// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelAddStageResponse AddStageResponse returns the stage ID of the created stage
// swagger:model modelAddStageResponse
type ModelAddStageResponse struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`
}

// Validate validates this model add stage response
func (m *ModelAddStageResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelAddStageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAddStageResponse) UnmarshalBinary(b []byte) error {
	var res ModelAddStageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
