// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelFaasInvocationCompletedEvent A call to the FaaS completed
// swagger:model modelFaasInvocationCompletedEvent
type ModelFaasInvocationCompletedEvent struct {

	// call id
	CallID string `json:"call_id,omitempty"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// result
	Result *ModelCompletionResult `json:"result,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// ts
	Ts strfmt.DateTime `json:"ts,omitempty"`
}

// Validate validates this model faas invocation completed event
func (m *ModelFaasInvocationCompletedEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResult(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelFaasInvocationCompletedEvent) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(m.Result) { // not required
		return nil
	}

	if m.Result != nil {

		if err := m.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelFaasInvocationCompletedEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelFaasInvocationCompletedEvent) UnmarshalBinary(b []byte) error {
	var res ModelFaasInvocationCompletedEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
