// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelDelayScheduledEvent A delay has started - this marks the relative start of an event when a delay node is recovered
// swagger:model modelDelayScheduledEvent
type ModelDelayScheduledEvent struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// time ms
	TimeMs int64 `json:"time_ms,omitempty"`

	// ts
	Ts strfmt.DateTime `json:"ts,omitempty"`
}

// Validate validates this model delay scheduled event
func (m *ModelDelayScheduledEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelDelayScheduledEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelDelayScheduledEvent) UnmarshalBinary(b []byte) error {
	var res ModelDelayScheduledEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
