// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelAddStageRequest AddStageRequest adds a new stage with dependenencies to the graph
// swagger:model modelAddStageRequest
type ModelAddStageRequest struct {

	// caller id
	CallerID string `json:"caller_id,omitempty"`

	// closure
	Closure *ModelBlobDatum `json:"closure,omitempty"`

	// code location
	CodeLocation string `json:"code_location,omitempty"`

	// deps
	Deps []string `json:"deps"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// operation
	Operation ModelCompletionOperation `json:"operation,omitempty"`
}

// Validate validates this model add stage request
func (m *ModelAddStageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClosure(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDeps(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOperation(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelAddStageRequest) validateClosure(formats strfmt.Registry) error {

	if swag.IsZero(m.Closure) { // not required
		return nil
	}

	if m.Closure != nil {

		if err := m.Closure.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("closure")
			}
			return err
		}
	}

	return nil
}

func (m *ModelAddStageRequest) validateDeps(formats strfmt.Registry) error {

	if swag.IsZero(m.Deps) { // not required
		return nil
	}

	return nil
}

func (m *ModelAddStageRequest) validateOperation(formats strfmt.Registry) error {

	if swag.IsZero(m.Operation) { // not required
		return nil
	}

	if err := m.Operation.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("operation")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelAddStageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAddStageRequest) UnmarshalBinary(b []byte) error {
	var res ModelAddStageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
