// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelGraphRequestProcessedResponse model graph request processed response
// swagger:model modelGraphRequestProcessedResponse
type ModelGraphRequestProcessedResponse struct {

	// flow id
	FlowID string `json:"flow_id,omitempty"`
}

// Validate validates this model graph request processed response
func (m *ModelGraphRequestProcessedResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGraphRequestProcessedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGraphRequestProcessedResponse) UnmarshalBinary(b []byte) error {
	var res ModelGraphRequestProcessedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
