// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelAddDelayStageRequest AddDelayStageRequest creates a delay stage
// swagger:model modelAddDelayStageRequest
type ModelAddDelayStageRequest struct {

	// caller id
	CallerID string `json:"caller_id,omitempty"`

	// code location
	CodeLocation string `json:"code_location,omitempty"`

	// delay ms
	DelayMs int64 `json:"delay_ms,omitempty"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`
}

// Validate validates this model add delay stage request
func (m *ModelAddDelayStageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelAddDelayStageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAddDelayStageRequest) UnmarshalBinary(b []byte) error {
	var res ModelAddDelayStageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
