// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelStageComposedEvent A stage was composed into  stage_id  - stage_id will compelete with the saem result as composed_stage_id
// swagger:model modelStageComposedEvent
type ModelStageComposedEvent struct {

	// composed stage id
	ComposedStageID string `json:"composed_stage_id,omitempty"`

	// flow id
	FlowID string `json:"flow_id,omitempty"`

	// stage id
	StageID string `json:"stage_id,omitempty"`

	// ts
	Ts strfmt.DateTime `json:"ts,omitempty"`
}

// Validate validates this model stage composed event
func (m *ModelStageComposedEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelStageComposedEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelStageComposedEvent) UnmarshalBinary(b []byte) error {
	var res ModelStageComposedEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
